INSERT INTO positions VALUES (DEFAULT,5,'проектировщик','уборка территории');
INSERT INTO positions VALUES (DEFAULT,2,'автослесарь','работа с документами');
INSERT INTO positions VALUES (DEFAULT,1,'строитель','управление командой');
INSERT INTO positions VALUES (DEFAULT,1,'строитель','работа с документами');
INSERT INTO positions VALUES (DEFAULT,5,'веб-дизайнер','управление командой');
INSERT INTO positions VALUES (DEFAULT,10,'веб-разработчик','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,6,'руководитель','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,5,'строитель','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,3,'аналитик','работа с документами');
INSERT INTO positions VALUES (DEFAULT,5,'аналитик','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,2,'юрист','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,1,'строитель','уборка территории');
INSERT INTO positions VALUES (DEFAULT,9,'веб-разработчик','уборка территории');
INSERT INTO positions VALUES (DEFAULT,8,'веб-разработчик','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,5,'проектировщик','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,6,'менеджер','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,7,'аналитик','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,1,'руководитель','уборка территории');
INSERT INTO positions VALUES (DEFAULT,8,'автослесарь','уборка территории');
INSERT INTO positions VALUES (DEFAULT,4,'веб-разработчик','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,8,'менеджер','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,1,'менеджер','управление командой');
INSERT INTO positions VALUES (DEFAULT,10,'повар','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,8,'автослесарь','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,1,'юрист','управление командой');
INSERT INTO positions VALUES (DEFAULT,6,'веб-дизайнер','управление командой');
INSERT INTO positions VALUES (DEFAULT,9,'аналитик','работа с документами');
INSERT INTO positions VALUES (DEFAULT,3,'повар','управление командой');
INSERT INTO positions VALUES (DEFAULT,6,'автослесарь','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,8,'проектировщик','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,9,'руководитель','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,6,'юрист','работа с документами');
INSERT INTO positions VALUES (DEFAULT,3,'проектировщик','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,6,'автослесарь','уборка территории');
INSERT INTO positions VALUES (DEFAULT,7,'автослесарь','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,7,'автослесарь','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,10,'проектировщик','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,4,'аналитик','управление командой');
INSERT INTO positions VALUES (DEFAULT,7,'веб-разработчик','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,5,'веб-дизайнер','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,7,'аналитик','управление командой');
INSERT INTO positions VALUES (DEFAULT,3,'менеджер','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,6,'строитель','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,9,'юрист','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,5,'веб-дизайнер','управление командой');
INSERT INTO positions VALUES (DEFAULT,9,'аналитик','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,3,'строитель','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,5,'аналитик','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,6,'автослесарь','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,6,'веб-дизайнер','работа с документами');
INSERT INTO positions VALUES (DEFAULT,6,'проектировщик','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,2,'веб-разработчик','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,5,'проектировщик','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,6,'руководитель','уборка территории');
INSERT INTO positions VALUES (DEFAULT,6,'юрист','работа с документами');
INSERT INTO positions VALUES (DEFAULT,4,'строитель','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,7,'веб-разработчик','уборка территории');
INSERT INTO positions VALUES (DEFAULT,8,'аналитик','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,7,'менеджер','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,5,'строитель','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,5,'руководитель','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,9,'руководитель','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,10,'веб-разработчик','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,7,'веб-разработчик','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,5,'автослесарь','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,4,'проектировщик','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,10,'веб-разработчик','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,9,'автослесарь','работа с документами');
INSERT INTO positions VALUES (DEFAULT,8,'автослесарь','управление командой');
INSERT INTO positions VALUES (DEFAULT,5,'аналитик','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,10,'руководитель','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,10,'строитель','управление командой');
INSERT INTO positions VALUES (DEFAULT,9,'веб-дизайнер','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,4,'веб-разработчик','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,7,'юрист','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,7,'аналитик','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,2,'веб-разработчик','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,8,'автослесарь','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,2,'проектировщик','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,5,'веб-дизайнер','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,1,'веб-разработчик','рисование диаграм');
INSERT INTO positions VALUES (DEFAULT,9,'автослесарь','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,6,'проектировщик','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,9,'строитель','уборка территории');
INSERT INTO positions VALUES (DEFAULT,8,'аналитик','работа с документами');
INSERT INTO positions VALUES (DEFAULT,10,'руководитель','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,1,'проектировщик','управление командой');
INSERT INTO positions VALUES (DEFAULT,9,'веб-дизайнер','веб-разработка');
INSERT INTO positions VALUES (DEFAULT,7,'строитель','работа с документами');
INSERT INTO positions VALUES (DEFAULT,5,'строитель','работа с документами');
INSERT INTO positions VALUES (DEFAULT,1,'автослесарь','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,3,'повар','управление командой');
INSERT INTO positions VALUES (DEFAULT,10,'строитель','уборка территории');
INSERT INTO positions VALUES (DEFAULT,4,'строитель','стратегическое планирование');
INSERT INTO positions VALUES (DEFAULT,9,'веб-разработчик','общение с клиентами');
INSERT INTO positions VALUES (DEFAULT,7,'менеджер','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,7,'повар','управление командой');
INSERT INTO positions VALUES (DEFAULT,2,'строитель','покупка рекламы');
INSERT INTO positions VALUES (DEFAULT,1,'веб-дизайнер','управление командой');
INSERT INTO positions VALUES (DEFAULT,3,'веб-дизайнер','покупка рекламы');
